config/routes.rb
Rails.application.routes.draw do
  resources :user_receipts
  resources :favourite_managers
  resources :product_checkout_details
  resources :receipts
  resources :users
  resources :categories
  resources :products
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get "checkout/:id", to: "products#new_checkout"
  get "cart", to: 'products#cart'
  post "checkout", to: "products#checkout"
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  post "product_checkout_details/add_quantity/:id", to: "products#add_quantity", as: "add_quantity"
  post "product_checkout_details/subtract_quantity/:id", to: "products#subtract_quantity", as: "subtract_quantity"
  delete "product_checkout_details/remove_product_in_cart/:id", to: "products#remove_product_in_cart", as: "remove_product_in_cart"
  get "search", to: "products#search"
  get "sort", to: "products#sort"
  get "favourites", to: 'products#favourites'
  post "products/add_to_favourite/:id", to: "products#add_to_favourite", as: "add_to_favourite"
  delete "products/remove_from_favourite/:id", to: "products#remove_from_favourite", as: "remove_from_favourite"
  post "products/add_to_favourite2/:id", to: "products#add_to_favourite2", as: "add_to_favourite2"
  delete "products/remove_from_favourite2/:id", to: "products#remove_from_favourite2", as: "remove_from_favourite2"
  post "update_profile/:id", to: 'users#update_profile'
  get "register", to: 'users#new'
  post 'register', to: 'users#create_user'
  get "change_password", to: 'users#change_password'
  post "change_password", to: 'users#save_change_password'
end

app/models/product_checkout_detail.rb
class ProductCheckoutDetail < ApplicationRecord
end

app/controllers/product_checkout_details_controller.rb
class ProductCheckoutDetailsController < ApplicationController
  before_action :set_product_checkout_detail, only: %i[ show edit update destroy ]

  # GET /product_checkout_details or /product_checkout_details.json
  def index
    @product_checkout_details = ProductCheckoutDetail.all
  end

  # GET /product_checkout_details/1 or /product_checkout_details/1.json
  def show
  end

  # GET /product_checkout_details/new
  def new
    @product_checkout_detail = ProductCheckoutDetail.new

  end

  # GET /product_checkout_details/1/edit
  def edit
  end

  # POST /product_checkout_details or /product_checkout_details.json
  def create
    @product_checkout_detail = ProductCheckoutDetail.new(product_checkout_detail_params)

    respond_to do |format|
      if @product_checkout_detail.save
        format.html { redirect_to product_checkout_detail_url(@product_checkout_detail), notice: "Product checkout detail was successfully created." }
        format.json { render :show, status: :created, location: @product_checkout_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_checkout_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_checkout_details/1 or /product_checkout_details/1.json
  def update
    respond_to do |format|
      if @product_checkout_detail.update(product_checkout_detail_params)
        format.html { redirect_to product_checkout_detail_url(@product_checkout_detail), notice: "Product checkout detail was successfully updated." }
        format.json { render :show, status: :ok, location: @product_checkout_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_checkout_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_checkout_details/1 or /product_checkout_details/1.json
  def destroy
    @product_checkout_detail.destroy

    respond_to do |format|
      format.html { redirect_to product_checkout_details_url, notice: "Product checkout detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_checkout_detail
      @product_checkout_detail = ProductCheckoutDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_checkout_detail_params
      params.require(:product_checkout_detail).permit(:name, :price, :quantity)
    end
end

app/helpers/product_checkout_details_helper.rb
module ProductCheckoutDetailsHelper
end

app/views/product_checkout_details/_form.html.erb
<%= form_with(model: product_checkout_detail) do |form| %>
  <% if product_checkout_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_checkout_detail.errors.count, "error") %> prohibited this product_checkout_detail from being saved:</h2>

      <ul>
        <% product_checkout_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/product_checkout_details/_product_checkout_detail.html.erb
<div id="<%= dom_id product_checkout_detail %>">
  <p>
    <strong>Name:</strong>
    <%= product_checkout_detail.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product_checkout_detail.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= button_to "Add", add_quantity_path(product_checkout_detail) %>
    <div><%= product_checkout_detail.quantity %></div>
    <%= button_to "Subtract", subtract_quantity_path(product_checkout_detail) %>
  </p>

</div>

app/views/product_checkout_details/edit.html.erb
<h1>Editing product checkout detail</h1>

<%= render "form", product_checkout_detail: @product_checkout_detail %>

<br>

<div>
  <%= link_to "Show this product checkout detail", @product_checkout_detail %> |
  <%= link_to "Back to product checkout details", product_checkout_details_path %>
</div>

app/views/product_checkout_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Product checkout details</h1>

<div id="product_checkout_details">
  <% @product_checkout_details.each do |product_checkout_detail| %>
    <%= render product_checkout_detail %>
    <p>
      <%= link_to "Show this product checkout detail", product_checkout_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New product checkout detail", new_product_checkout_detail_path %>

app/views/product_checkout_details/new.html.erb
<h1>New product checkout detail</h1>

<%= render "form", product_checkout_detail: @product_checkout_detail %>

<br>

<div>
  <%= link_to "Back to product checkout details", product_checkout_details_path %>
</div>

app/views/product_checkout_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_checkout_detail %>

<div>
  <%= link_to "Edit this product checkout detail", edit_product_checkout_detail_path(@product_checkout_detail) %> |
  <%= link_to "Back to product checkout details", product_checkout_details_path %>

  <%= button_to "Destroy this product checkout detail", @product_checkout_detail, method: :delete %>
</div>