config/routes.rb
Rails.application.routes.draw do
  resources :user_receipts
  resources :favourite_managers
  resources :product_checkout_details
  resources :receipts
  resources :users
  resources :categories
  resources :products
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get "checkout/:id", to: "products#new_checkout"
  get "cart", to: 'products#cart'
  post "checkout", to: "products#checkout"
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  post "product_checkout_details/add_quantity/:id", to: "products#add_quantity", as: "add_quantity"
  post "product_checkout_details/subtract_quantity/:id", to: "products#subtract_quantity", as: "subtract_quantity"
  delete "product_checkout_details/remove_product_in_cart/:id", to: "products#remove_product_in_cart", as: "remove_product_in_cart"
  get "search", to: "products#search"
  get "sort", to: "products#sort"
  get "favourites", to: 'products#favourites'
  post "products/add_to_favourite/:id", to: "products#add_to_favourite", as: "add_to_favourite"
  delete "products/remove_from_favourite/:id", to: "products#remove_from_favourite", as: "remove_from_favourite"
  post "products/add_to_favourite2/:id", to: "products#add_to_favourite2", as: "add_to_favourite2"
  delete "products/remove_from_favourite2/:id", to: "products#remove_from_favourite2", as: "remove_from_favourite2"
  post "update_profile/:id", to: 'users#update_profile'
  get "register", to: 'users#new'
  post 'register', to: 'users#create_user'
  get "change_password", to: 'users#change_password'
  post "change_password", to: 'users#save_change_password'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_receipts, dependent: :destroy
  has_many :favourite_managers
  has_many :products, through: :favourite_managers
  validates :account, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX}
  has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:new, :create, :show, :index, :create_user, :new_user]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create_user
    @user = User.new
    @user.account = params[:account]
    @user.name = params[:name]
    @user.email = params[:email]
    @user.phone = params[:phone]
    @user.password = params[:password]
    @user.admin = false
    @user.save
    redirect_to login_path
  end

  def new_user
    @user = User.new

  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def update_profile
    @user = User.find(params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    @user.phone = params[:phone]
    @user.save
  end

  def change_password
  end

  def save_change_password
    if current_user.authenticate(params[:old_password]) != false
      if params[:new_password] == params[:new_password_confirmation]
        user = User.find_by(id: current_user.id)
        user.password = params[:new_password]
        user.save!
        flash[:notice] = "Changed password successfully"
        redirect_to products_path
      else
        flash[:notice] = "New password and password confirmation not match"
        render 'change_password'
      end
    else
      flash[:notice] = "Password incorrect!"
      render 'change_password'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:account, :name, :email, :phone, :password)
    end

    def require_same_user
      if current_user != @user
        flash[:danger] = "You can only edit or delete your own information"
        redirect_to users_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :account, style: "display: block" %>
    <%= form.text_field :account %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Account:</strong>
    <%= user.account %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

</div>

app/views/users/change_password.html.erb
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link
  href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;600;700&display=swap"
  rel="stylesheet"/>
<style>
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  h1 {
    font-weight: 600;
  }
  html {
    font-family: "Rubik", sans-serif;
    color: #444;
  }
  .main-container {
      display: flex;
      justify-content: space-between;
      text-align: center;
      background: #f8f9fa;
    }

    .content-container {
      position: relative;
      display: flex;
      align-items: center;
      width: 800px;
      animation-duration: 1s;
      animation-name: slidein;
      overflow: hidden;
    }

    @keyframes slidein {
      from {
        margin-left: 100%;
        width: 900px;
      }

      to {
        margin-right: 0%;
        width: 900px;
      }
    }

    .img-container {
      height: 100vh;
      background-image: url("../assets/meal-8.jpg");
      background-size: cover;

      width: 100%;
      overflow: hidden;
    }

    .login-section {
      width: 400px;
      position: absolute;
      top: 22%;
      transform: translateX(60px);
    }

    .heading {
      margin-bottom: 40px;
      text-align: center;
    }

    .button {
      margin-top: 20px;
      width: 100%;
      font-weight: 600;
      background-color: #e67e22;
      color: #fff;
      text-decoration: none;
      padding: 15px;
      cursor: pointer;
      border-radius: 5px;
      border: none;
      text-transform: uppercase;
      margin-bottom: 20px;
    }

    .form {
      padding: 13px;
      width: 100%;
      border-radius: 5px;
      border: 1px solid #ccc;
      font-size: 1rem;
    }

    .OR {
      margin-bottom: 20px;
    }

    .register:link,
    .register:visited {
      text-decoration: none;
      color: #e67e22;
      font-size: 20px;
    }

    .register:active,
    .register:hover {
      color: #e67e22;
      text-decoration: underline;
      text-underline-offset: 3px;
      text-decoration-thickness: 1px;
    }
</style>


<body>
    <div class="main-container">
      <div class="img-container"></div>
      <div class="content-container">
        <div class="login-section">
          <h1 class="heading">Change your password</h1>
          <%= form_with(url: change_password_path, local: true) do |form| %>
            <div>
              <%= form.text_field :old_password, type: "password", class: "form", size: "30", placeholder: "Old password", style: "margin-bottom: 15px" %>
            </div>
            <div>
              <%= form.text_field :new_password, type: "password",class: "form", size: "30", placeholder: "New password", style: "margin-bottom: 15px" %>
            </div>
            <div>
              <%= form.text_field :new_password_confirmation, type: "password", class: "form", size: "30", placeholder: "Confirm your password", style: "margin-bottom: 15px" %>
            </div>
            <div>
              <%= button_to "Save", change_password_path, method: :post, class: "button", style: "margin-bottom: 50px" %>
            </div>
          <% end %>

            <a href="/products" class="register"> Back to products page &rarr; </a>
          </form>
        </div>
      </div>
    </div>
  </body>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link
  href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;600;700&display=swap"
  rel="stylesheet"/>
<style>
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  h1 {
    font-weight: 600;
  }
  html {
    font-family: "Rubik", sans-serif;
    color: #444;
  }
  .main-container {
      display: flex;
      justify-content: space-between;
      text-align: center;
      background: #f8f9fa;
    }

    .content-container {
      position: relative;
      display: flex;
      align-items: center;
      width: 800px;
      animation-duration: 1s;
      animation-name: slidein;
      overflow: hidden;
    }

    @keyframes slidein {
      from {
        margin-left: 100%;
        width: 900px;
      }

      to {
        margin-right: 0%;
        width: 900px;
      }
    }

    .img-container {
      height: 100vh;
      background-image: url("../assets/meal-8.jpg");
      background-size: cover;

      width: 100%;
      overflow: hidden;
    }

    .login-section {
      width: 400px;
      position: absolute;
      top: 22%;
      transform: translateX(60px);
    }

    .heading {
      margin-bottom: 40px;
      text-align: center;
    }

    .button {
      margin-top: 20px;
      width: 100%;
      font-weight: 600;
      background-color: #e67e22;
      color: #fff;
      text-decoration: none;
      padding: 15px;
      cursor: pointer;
      border-radius: 5px;
      border: none;
      text-transform: uppercase;
      margin-bottom: 20px;
    }

    .form {
      padding: 13px;
      width: 100%;
      border-radius: 5px;
      border: 1px solid #ccc;
      font-size: 1rem;
    }

    .OR {
      margin-bottom: 20px;
    }

    .register:link,
    .register:visited {
      text-decoration: none;
      color: #e67e22;
      font-size: 20px;
    }

    .register:active,
    .register:hover {
      color: #e67e22;
      text-decoration: underline;
      text-underline-offset: 3px;
      text-decoration-thickness: 1px;
    }
</style>


<body>
    <div class="main-container">
      <div class="img-container"></div>
      <div class="content-container">
        <div class="login-section">
          <h1 class="heading">Register form</h1>
          <%= form_with(url: register_path, local: true) do |form| %>
            <div>
              <%= form.text_field :account, class: "form", size: "30", placeholder: "Type your account here", style: "margin-bottom: 15px" %>
            </div>
            <div>
              <%= form.text_field :name, class: "form", size: "30", placeholder: "Type your name here", style: "margin-bottom: 15px" %>
            </div>
            <div>
              <%= form.text_field :email, class: "form", size: "30", placeholder: "Type your email here", style: "margin-bottom: 15px" %>
            </div>
            <div>
              <%= form.text_field :phone, class: "form", size: "30", placeholder: "Type your phone number here", style: "margin-bottom: 15px" %>
            </div>
            <div>

              <%= form.password_field :password, class: "form OR", placeholder: "Type your password in here" %>
            </div>

            <div>
              <%= button_to "Register", register_path, method: :post, class: "button", style: "margin-bottom: 50px" %>
            </div>
          <% end %>

            <a href="/products" class="register"> Back to products page &rarr; </a>
          </form>
        </div>
      </div>
    </div>
  </body>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>