config/routes.rb
Rails.application.routes.draw do
  resources :user_receipts
  resources :favourite_managers
  resources :product_checkout_details
  resources :receipts
  resources :users
  resources :categories
  resources :products
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get "checkout/:id", to: "products#new_checkout"
  get "cart", to: 'products#cart'
  post "checkout", to: "products#checkout"
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  post "product_checkout_details/add_quantity/:id", to: "products#add_quantity", as: "add_quantity"
  post "product_checkout_details/subtract_quantity/:id", to: "products#subtract_quantity", as: "subtract_quantity"
  delete "product_checkout_details/remove_product_in_cart/:id", to: "products#remove_product_in_cart", as: "remove_product_in_cart"
  get "search", to: "products#search"
  get "sort", to: "products#sort"
  get "favourites", to: 'products#favourites'
  post "products/add_to_favourite/:id", to: "products#add_to_favourite", as: "add_to_favourite"
  delete "products/remove_from_favourite/:id", to: "products#remove_from_favourite", as: "remove_from_favourite"
  post "products/add_to_favourite2/:id", to: "products#add_to_favourite2", as: "add_to_favourite2"
  delete "products/remove_from_favourite2/:id", to: "products#remove_from_favourite2", as: "remove_from_favourite2"
  post "update_profile/:id", to: 'users#update_profile'
  get "register", to: 'users#new'
  post 'register', to: 'users#create_user'
  get "change_password", to: 'users#change_password'
  post "change_password", to: 'users#save_change_password'
end

app/models/user_receipt.rb
class UserReceipt < ApplicationRecord
  has_one_attached :file
  belongs_to :user
end

app/controllers/user_receipts_controller.rb
class UserReceiptsController < ApplicationController
  before_action :set_user_receipt, only: %i[ show edit update destroy ]

  # GET /user_receipts or /user_receipts.json
  def index
    @user_receipts = UserReceipt.all
  end

  # GET /user_receipts/1 or /user_receipts/1.json
  def show
  end

  # GET /user_receipts/new
  def new
    @user_receipt = UserReceipt.new
  end

  # GET /user_receipts/1/edit
  def edit
  end

  # POST /user_receipts or /user_receipts.json
  def create
    @user_receipt = UserReceipt.new(user_receipt_params)

    respond_to do |format|
      if @user_receipt.save
        format.html { redirect_to user_receipt_url(@user_receipt), notice: "User receipt was successfully created." }
        format.json { render :show, status: :created, location: @user_receipt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_receipts/1 or /user_receipts/1.json
  def update
    respond_to do |format|
      if @user_receipt.update(user_receipt_params)
        format.html { redirect_to user_receipt_url(@user_receipt), notice: "User receipt was successfully updated." }
        format.json { render :show, status: :ok, location: @user_receipt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_receipts/1 or /user_receipts/1.json
  def destroy
    @user_receipt.destroy

    respond_to do |format|
      format.html { redirect_to user_receipts_url, notice: "User receipt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_receipt
      @user_receipt = UserReceipt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_receipt_params
      params.require(:user_receipt).permit(:name, :phone, :address, :total)
    end
end

app/helpers/user_receipts_helper.rb
module UserReceiptsHelper
end

app/views/user_receipts/_form.html.erb
<%= form_with(model: user_receipt) do |form| %>
  <% if user_receipt.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_receipt.errors.count, "error") %> prohibited this user_receipt from being saved:</h2>

      <ul>
        <% user_receipt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.number_field :total %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_receipts/_user_receipt.html.erb
<div id="<%= dom_id user_receipt %>">
  <p>
    <strong>Name:</strong>
    <%= user_receipt.name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user_receipt.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user_receipt.address %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= user_receipt.total %>
  </p>

  <p>
    <strong>Show details: </strong>
    <% if user_receipt.file.previewable? %>
    <%= link_to user_receipt.name, rails_blob_path(user_receipt.file, disposition: "inline") %>
    <% end %>
</div>

app/views/user_receipts/edit.html.erb
<h1>Editing user receipt</h1>

<%= render "form", user_receipt: @user_receipt %>

<br>

<div>
  <%= link_to "Show this user receipt", @user_receipt %> |
  <%= link_to "Back to user receipts", user_receipts_path %>
</div>

app/views/user_receipts/index.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "products", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "show_product", "data-turbo-track": "reload" %>
<p style="color: green"><%= notice %></p>
<style>
/*
    SPACING SYSTEM (px)
    2 / 4 / 8 / 12 / 16 / 24 / 32 / 48 / 64 / 80 / 96 / 128
    FONT SIZE SYSTEM (px)
    10 / 12 / 14 / 16 / 18 / 20 / 24 / 30 / 36 / 44 / 52 / 62 / 74 / 86 / 98
    */
/*
    GREY COLOR: #343a40
    */

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    main {

    }
    table {
      width: 1200px;
      margin-top: 20px;
      font-size: 18px;
      /* border: 1px solid #343a40; */
      border-collapse: collapse;
      border-radius: 9px;
      overflow: hidden;
      margin-bottom: 50px;
    }

    th,
    td {
      /* border: 1px solid #343a40; */
      padding: 36px 40px;
      text-align: left;
    }

    thead tr {
      background-color: #343a40;
      color: #fff;
    }

    thead th {
      width: 25%;
    }

    tbody tr:nth-child(odd) {
      background-color: #f8f9fa;
    }

    tbody tr:nth-child(even) {
      background-color: #e9ecef;
    }

    .checkout--info--container {
      width: 300px;
      padding: 20px;
      height: 270px;
      background: rgb(256, 256, 256, 0.8);
      margin-top: 90px;
      box-shadow: 0px 3px 6px 0px rgb(0 0 0 / 10%), 0px 1px 3px 0px rgb(0 0 0 / 8%);
    }
    .cart--info--backlink:link,
    .cart--info--backlink:visited {
      display: inline-block;
      padding-top: 30px;
      color: #555;
      text-decoration: none;
      font-size: 2.5rem;
      margin-left: 130px;
    }

    .cart--info--backlink:hover,
    .cart--info--backlink:active {
      text-decoration: underline;
      text-underline-offset: 3px;
      text-decoration-thickness: 2px;
    }

    body {

  position: relative;
}




</style>

<header class="header " >
      <a href="/products" class="main-nav-link" style="font-size: 3rem;">
        Fastfood
      </a>

      <nav class="main-nav" >
        <ul class="main-nav-list">
          <li><a class="main-nav-link" style="font-size: 2rem">Manage account</a></li>
          <li><a class="main-nav-link" href="/user_receipts">Order history</a></li>
          <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :post, data: {"turbo-method": :delete}, class: "main-nav-link" %></li>
          <% else %>
          <li>
            <div><%= link_to 'LOGIN', login_path, class: "main-nav-link"  %></div>
          </li>
          <% end %>
          <li><a class="main-nav-link" href="favourites">Favourites</a></li>
          <li><a class="main-nav-link nav-cta" href="/cart">Your Cart</a></li>
        </ul>
      </nav>

      <button class="btn-mobile-nav">
        <ion-icon class="icon-mobile-nav" name="menu-outline"></ion-icon>
        <ion-icon class="icon-mobile-nav" name="close-outline"></ion-icon>
      </button>
    </header>

<body>

  <main>
    <div>
      <div>
        <a href="#" class="cart--info--backlink" style="font-size: 30px; margin-top: 30px">Order history:</a>
      </div>
      <div style="display: flex; justify-content: center">
        <table>
          <thead>
            <tr>

              <th>Date ordered</th>
              <th>Total</th>
              <th>Ship to address:</th>
              <th>PDF</th>
            </tr>
          </thead>

          <tbody>

          <% @user_receipts.each do |user_receipt| %>
              <tr>

                <th><%= user_receipt.created_at %></th>
                <td><%= user_receipt.total %> VND</td>
                <td><%= user_receipt.address %></td>
                <td >
                  <% if user_receipt.file.previewable? %>
                    <%= link_to "Show details", rails_blob_path(user_receipt.file, disposition: "inline") %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    </div>
    </main>

</body>
<div id="user_receipts">
  <% @user_receipts.each do |user_receipt| %>
    <% if user_receipt.user_id == current_user.id %>
      <%= render user_receipt %>
      <p>
        <%= link_to "Show this user receipt", user_receipt %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/user_receipts/new.html.erb
<h1>New user receipt</h1>

<%= render "form", user_receipt: @user_receipt %>

<br>

<div>
  <%= link_to "Back to user receipts", user_receipts_path %>
</div>

app/views/user_receipts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_receipt %>

<div>
  <%= link_to "Edit this user receipt", edit_user_receipt_path(@user_receipt) %> |
  <%= link_to "Back to user receipts", user_receipts_path %>

  <%= button_to "Destroy this user receipt", @user_receipt, method: :delete %>
</div>