config/routes.rb
Rails.application.routes.draw do
  resources :user_receipts
  resources :favourite_managers
  resources :product_checkout_details
  resources :receipts
  resources :users
  resources :categories
  resources :products
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get "checkout/:id", to: "products#new_checkout"
  get "cart", to: 'products#cart'
  post "checkout", to: "products#checkout"
  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
  post "product_checkout_details/add_quantity/:id", to: "products#add_quantity", as: "add_quantity"
  post "product_checkout_details/subtract_quantity/:id", to: "products#subtract_quantity", as: "subtract_quantity"
  delete "product_checkout_details/remove_product_in_cart/:id", to: "products#remove_product_in_cart", as: "remove_product_in_cart"
  get "search", to: "products#search"
  get "sort", to: "products#sort"
  get "favourites", to: 'products#favourites'
  post "products/add_to_favourite/:id", to: "products#add_to_favourite", as: "add_to_favourite"
  delete "products/remove_from_favourite/:id", to: "products#remove_from_favourite", as: "remove_from_favourite"
  post "products/add_to_favourite2/:id", to: "products#add_to_favourite2", as: "add_to_favourite2"
  delete "products/remove_from_favourite2/:id", to: "products#remove_from_favourite2", as: "remove_from_favourite2"
  post "update_profile/:id", to: 'users#update_profile'
  get "register", to: 'users#new'
  post 'register', to: 'users#create_user'
  get "change_password", to: 'users#change_password'
  post "change_password", to: 'users#save_change_password'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :image
  has_many :favourite_managers
  has_many :users, through: :favourite_managers
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :require_user, except: [:favourites, :show, :index, :search, :filter]
  before_action :require_admin, except: [:cart, :favourites, :search, :sort, :show, :index, :add_to_cart, :remove_from_cart, :checkout, :new_checkout, :add_quantity, :subtract_quantity,
  :add_to_favourite, :remove_from_favourite, :add_to_favourite2, :remove_from_favourite2, :remove_product_in_cart]

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to products_path
    @product_checkout_detail = ProductCheckoutDetail.new
    @product_checkout_detail.name = Product.find(id).name
    @product_checkout_detail.price = Product.find(id).price
    @product_checkout_detail.quantity = 1
    @product_checkout_detail.save
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    @product_checkout_detail = ProductCheckoutDetail.find_by(name: Product.find(id).name)
    if @product_checkout_detail.present?
      @product_checkout_detail.destroy
    end
    redirect_to products_path
  end

  def cart
    @product_checkout_details = ProductCheckoutDetail.all
  end

  def add_quantity
    id = params[:id].to_i
    @product_checkout_detail = ProductCheckoutDetail.find_by(id: id)
    @product_checkout_detail.quantity += 1
    @product_checkout_detail.save
    redirect_to cart_path
  end

  def subtract_quantity
    id = params[:id].to_i
    @product_checkout_detail = ProductCheckoutDetail.find_by(id: id)
    if(@product_checkout_detail.quantity >= 1)
      @product_checkout_detail.quantity -= 1
    end
    @product_checkout_detail.save
    redirect_to cart_path
  end

  def remove_product_in_cart
    id = params[:id].to_i
    cart_id = Product.find_by(name: ProductCheckoutDetail.find_by(id: id).name).id
    session[:cart].delete(cart_id)
    @product_checkout_detail = ProductCheckoutDetail.find_by(id: id)
    @product_checkout_detail.destroy
    redirect_to cart_path
  end

  $product_checkout_details
  def checkout
    @user_receipt = UserReceipt.new
      @product_checkout_details = ProductCheckoutDetail.all
      $product_checkout_details = ProductCheckoutDetail.all.clone
      total = 0
    if @product_checkout_details.present?
      @product_checkout_details.each do |product_checkout_detail|
        product_checkout_detail.save
        total = product_checkout_detail.price * product_checkout_detail.quantity + total
      end


    end
    @user_receipt.name = params[:name]
    @user_receipt.phone = params[:phone]
    @user_receipt.address = params[:address]
    @user_receipt.total = total
    @user_receipt.user_id = current_user.id
    @user_receipt.save
    session[:cart] = nil
    redirect_to "http://localhost:3000/checkout/#{@user_receipt.id}"
  end

  def new_checkout
    id = params[:id].to_i
    @user_receipt = UserReceipt.find_by(id: id)
    @product_checkout_details = ProductCheckoutDetail.all

    @r = Receipts::Receipt.new(

      details: [
        ["Receipt Number", "123"],
        ["Date paid", Date.today],
        ["Payment method", "Cash"]
      ],
      company: {
        name: "Fastfood",
        address: "So 1 Dai Co Viet",
        email: "Fastfood@gmail.com",

      },
      recipient: [

          @user_receipt.name,
          @user_receipt.address,
          @user_receipt.phone,
          nil,
          current_user.email

      ],

        line_items: [
          [nil, nil, nil, nil],
        ],

    )
    # @r.text("<font size='10' width='1000'>hello this is a test function</font> <font size='10'>hello this is a test function 2</font>", :inline_format => true, :single_line => true )
    # @r.text("<font size='10'>hello this is a test function 2</font>", :inline_format => true)
        @r.render_line_items([["<b>Here is your order detail:</b>"]])
    $product_checkout_details.each_with_index do |product_checkout_detail, index|


      @r.render_footer("<b>Item #{index + 1}</b>: #{product_checkout_detail.name}\nPrice: #{product_checkout_detail.price}\nQuantity: #{product_checkout_detail.quantity}\nTotal: #{product_checkout_detail.price * product_checkout_detail.quantity}")

    end
    @r.render_footer("<b>Total price: #{@user_receipt.total }</b>")
    respond_to do |format|
      format.html
      format.json
      format.pdf{send_data @r.render, disposition: :inline}
    end
    @r.render_file "receipt#{@user_receipt.id}.pdf"
    @user_receipt.file.attach(io: File.open("receipt#{@user_receipt.id}.pdf"), filename: "receipt#{@user_receipt.id}.pdf")
    @user_receipt.save
    ProductCheckoutDetail.delete_all


  end
  # GET /products or /products.json
  def index
    @products = Product.paginate(page: params[:page], per_page: 8)

    @product_checkout_details = ProductCheckoutDetail.all
  end

  def search
    @products = Product.where("name LIKE ?", "%" + params[:q] + "%")
  end

  def sort
    if params[:value].to_i == 1
      @products = Product.order(:price)
    elsif params[:value].to_i == 2
      @products = Product.order(price: :desc)
    elsif params[:value].to_i == 3
      @products = Product.where('price > 25000 AND price < 50000').order(price: :asc)
    elsif params[:value].to_i == 4
      @products = Product.where('price > 50000 AND price < 100000').order(price: :asc)
    elsif params[:value].to_i == 5
      @products = Product.where('price > 100000').order(price: :asc)
    end
  end
  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_to_favourite
    @favourite_manager = FavouriteManager.new
    @favourite_manager.user_id = current_user.id
    id = params[:id].to_i
    @favourite_manager.product_id = id
    @favourite_manager.save
    redirect_to products_path
  end

  def remove_from_favourite
    id = params[:id].to_i
    @favourite_manager = FavouriteManager.find_by(user_id: current_user.id, product_id: id)
    @favourite_manager.destroy

    redirect_to products_path
  end

  def add_to_favourite2
    @favourite_manager = FavouriteManager.new
    @favourite_manager.user_id = current_user.id
    id = params[:id].to_i
    @favourite_manager.product_id = id
    @favourite_manager.save
    redirect_to favourites_path
  end

  def remove_from_favourite2
    id = params[:id].to_i
    @favourite_manager = FavouriteManager.find_by(user_id: current_user.id, product_id: id)
    @favourite_manager.destroy

    redirect_to favourites_path
  end

  def favourites
    @favourite_managers = FavouriteManager.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])

    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :category_id)
    end






end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_filter.html.erb
<div class="margin-bottom-md category-img-flex" id="card-container">
        <div class="category-item-flex">
        <img
            src="assets/chicken.jpg"
            class="category-img" id="meal-img"
            alt="Chicken"
          />
          <p style="font-size: 2rem; font-weight: 500;">Chicken</p>
        </div>
        <div class="category-item-flex">
          <img
              src="assets/rice.jpg"
              class="category-img" id="meal-img"
              alt="Rice + Spaghetti"
              style = "max-width: 120px; aspect-ratio: 1/1"
            />
            <p style="font-size: 2rem; font-weight: 500">Rice + Spaghetti</p>
          </div>
          <div class="category-item-flex">
            <img
                src="assets/burger.jpg"
                class="category-img" id="meal-img"
                alt="Burger"
              />
              <p style="font-size: 2rem; font-weight: 500;">Burger</p>
            </div>
            <div class="category-item-flex">
              <img
                  src="assets/drink.jpg"
                  class="category-img" id="meal-img"
                  alt="Drink"
                />
                <p style="font-size: 2rem; font-weight: 500;">Drink</p>
              </div>
              <div class="category-item-flex">
                <img
                    src="assets/dessert.jpg"
                    class="category-img" id="meal-img"
                    alt="Dessert"
                  />
                  <p style="font-size: 2rem; font-weight: 500">Dessert</p>
                </div>
                <div class="category-item-flex">
                  <img
                      src="assets/promotion.jpg"
                      class="category-img" id="meal-img"
                      alt="Side Dish"
                    />
                    <p style="font-size: 2rem; font-weight: 500;">Side Dish</p>
                  </div>
      </div>


      <div class=" flex" id="card-container"  style="margin-bottom: 10rem;">
        <form class="tool-bar" action="/search">

          <button class="categories-selector"><div class="flex-categories">Searchbar
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 arrow-down" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
            </svg>
          </div> </button>

            <input class="search-bar" type="text" name="q" placeholder="Click here to search"></input>
            <button class="search-button-container" type="submit">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6 features-icon"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2"
                class="features-icon"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                />
              </svg>
            </button>


        </form>

        <form class="f-sort" action="/sort">
          <span class="sort-by">Sort by:</span
          ><select class="form-control" id="value" name="value" onchange ="this.form.submit()">
            <option value="0">Filter option</option>
            <option value="1">Price from low to high</option>
            <option value="2">Price from high to low</option>
            <option value="3">from 25000 to 50000</option>
            <option value="4">from 50000 to 100000</option>
            <option value="5">from 100000 and above</option>
          </select>
        </form>
      </div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>


  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.number_field :category_id, max: 7 %>
  </div>

  <div>
    <% if product.image.attached? %>
    <%= image_tag product.image, style: "width: 200px" %>
    <% end %>
    <%= form.label :image, style: "display: block; width: 200px" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_header.html.erb
<header class="header margin-bottom-md ">
      <a href="/products" class="main-nav-link" style="font-size: 3rem;">
        Fastfood
      </a>

      <nav class="main-nav">
        <ul class="main-nav-list">
          <li><a class="main-nav-link show-modal" style="font-weight: 500">Manage account</a></li>
          <li><a class="main-nav-link" href="/user_receipts">Order history</a></li>
          <li><a class="main-nav-link" href="/change_password">Change password</a></li>
          <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, data: {"turbo-method": :delete}, class: "main-nav-link", method: :post %></li>
          <% else %>
          <li>
            <div><%= link_to 'LOGIN', login_path, class: "main-nav-link"  %></div>
          </li>
          <% end %>
          <li><a class="main-nav-link" href="favourites">Favourites</a></li>
          <li><a class="main-nav-link nav-cta" href="/cart">Your Cart</a></li>
        </ul>
      </nav>

      <button class="btn-mobile-nav">
        <ion-icon class="icon-mobile-nav" name="menu-outline"></ion-icon>
        <ion-icon class="icon-mobile-nav" name="close-outline"></ion-icon>
      </button>
    </header>

app/views/products/_product.html.erb
<style>
  .detail-link:link, detail-link:visited {
    color: #555;
    text-decoration: none;

  }
  .detail-link:hover, .detail-link:active {
      color: #555;
      text-decoration: underline;
      text-underline-offset: 2px;
  }
</style>
<div class="meal" id="meal">
            <%= image_tag product.image, class: "meal-img", id: "meal-img", style: "height: 180px" %>
            <div class="meal-content" id="meal-content">
              <div class="meal-tags">
                <span class="tag tag--<%=Category.find_by(:id => product.category_id).name.downcase%>"><%= Category.find_by(:id => product.category_id).name.downcase %></span>
              </div>
              <p class="meal-title" id = "meal-title" style="height: 46px"><%= product.name %></p>
              <ul class="meal-attributes">

                <li class="meal-attribute">
                  <ion-icon
                    class="meal-icon"
                    name="restaurant-outline"
                  ></ion-icon>
                  <a  style="color: #555" class="detail-link" href="products/<%=product.id%>">Show detail<strong> &rarr;</strong></a>
                </li>
                <li class="meal-attribute">
                  <ion-icon class="meal-icon" name="cash-outline"></ion-icon>
                  <span><strong><%= product.price %></strong> VND</span>
                </li>
                <div class="meal-price">

                        <% if logged_in? && (FavouriteManager.find_by(user_id: current_user.id, product_id: product.id) == nil) %>
                          <%= button_to add_to_favourite_path(product), method: :post, style: "background: none; border: none; padding: 0" do %>
                            <ion-icon
                          name="heart-outline"
                          style="color: #f03e3e; width: 28px; height: 28px"
                        ></ion-icon>
                          <% end %>
                        <% else %>
                          <%= button_to remove_from_favourite_path(product), method: :delete, style: "background: none; border: none; padding: 0" do %>
                            <ion-icon
                          name="heart"
                          style="color: #f03e3e; width: 28px; height: 28px"
                        ></ion-icon>
                          <% end %>
                        <% end %>

                  <% if @cart.include?(product) %>
                    <%= button_to "Remove", remove_from_cart_path(product), method: :delete, class: "btn btn--small" %>
                  <% else %>
                    <%= button_to "Add to cart", add_to_cart_path(product), class: "btn btn--small" %>
                  <% end %>
                </div>
              </ul>
            </div>
          </div>

app/views/products/cart.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "products", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "show_product", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "cart", "data-turbo-track": "reload" %>
<script
      type="module"
      src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule=""
      src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.js"
    ></script>

    <script
      defer
      src="https://unpkg.com/smoothscroll-polyfill@0.4.4/dist/smoothscroll.min.js"
    ></script>
  <script defer src="js/script.js"></script>
<style>
/*
    SPACING SYSTEM (px)
    2 / 4 / 8 / 12 / 16 / 24 / 32 / 48 / 64 / 80 / 96 / 128
    FONT SIZE SYSTEM (px)
    10 / 12 / 14 / 16 / 18 / 20 / 24 / 30 / 36 / 44 / 52 / 62 / 74 / 86 / 98
    */
/*
    GREY COLOR: #343a40
    */

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    main {
      display: flex;
      justify-content: space-evenly;
      position: relative;
      min-height: 100vh;
      background-image: linear-gradient(
          rgba(34, 34, 34, 0.603),
          rgba(34, 34, 34, 0.603)
        ),
        url("assets/meal-9.jpg");
      background-size: cover;
    }
    table {
      width: 900px;
      margin-top: 20px;
      font-size: 18px;
      /* border: 1px solid #343a40; */
      border-collapse: collapse;
      border-radius: 9px;
      overflow: hidden;
      margin-bottom: 50px;
    }

    th,
    td {
      /* border: 1px solid #343a40; */
      padding: 24px 16px;
      text-align: left;
    }

    thead tr {
      background-color: #343a40;
      color: #fff;
    }

    thead th {
      width: 25%;
    }

    tbody tr:nth-child(odd) {
      background-color: #f8f9fa;
    }

    tbody tr:nth-child(even) {
      background-color: #e9ecef;
    }

    .checkout--info--container {
      width: 300px;
      padding: 20px;
      height: 270px;
      background: rgb(256, 256, 256, 0.8);
      margin-top: 90px;
      box-shadow: 0px 3px 6px 0px rgb(0 0 0 / 10%), 0px 1px 3px 0px rgb(0 0 0 / 8%);
    }
    .cart--info--backlink:link,
    .cart--info--backlink:visited {
      display: inline-block;
      padding-top: 30px;
      color: #fff;
      text-decoration: none;
      font-size: 2.5rem;
      margin-left: 0;
    }

    .cart--info--backlink:hover,
    .cart--info--backlink:active {
      text-decoration: underline;
      text-underline-offset: 3px;
      text-decoration-thickness: 2px;
    }
    .orange-button {
      margin-top: 20px;
      margin-bottom: 15px;
      width: 100%;
      font-weight: 600;
      background-color: #fd7e14;
      color: #fff;
      text-decoration: none;
      padding-top: 20px;
      padding-bottom: 20px;
      padding: 15px;
      cursor: pointer;
      font-size: 15px;
      border-radius: 5px;
      border: none;
      text-transform: uppercase;
    }
    .orange-button:hover {
      background-color: #f76707;
    }
    .green-button {
      padding-top: 20px;
      padding-bottom: 20px;
      font-size: 15px;
      margin-bottom: 15px;
      width: 100%;
      font-weight: 600;
      background-color: #2f9e44;
      color: #fff;
      text-decoration: none;
      padding: 15px;
      cursor: pointer;
      border-radius: 5px;
      border: none;
      text-transform: uppercase;
    }
    .green-button:hover {
      background-color: #2b8a3e;
    }
    .total--price--field {
      font-size: 3.5rem;
      font-weight: 600;
      text-align: center;
    }
    body {

  position: relative;
}

.show-modal {

  cursor: pointer;
}

.close-modal {
  position: absolute;
  top: 1.2rem;
  right: 2rem;
  font-size: 5rem;
  color: #333;
  cursor: pointer;
  border: none;
  background: none;
}
.hidden {
  display: none;
}

.modal {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 80%;


  padding: 6rem;
  border-radius: 5px;
  box-shadow: 0 3rem 5rem rgba(0, 0, 0, 0.3);
  z-index: 10;
  font-size: 1.8rem;
}

.overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.6);
  backdrop-filter: blur(3px);
  z-index: 5;
}
</style>
  <body>

  <main>
    <div>
      <div>
        <a href="#" class="cart--info--backlink" style="font-size: 30px; margin-top: 30px">Cart information:</a>
      </div>
      <div style="display: flex; justify-content: center">
        <table>
          <thead>
            <tr>
              <th style="width: 80px"></th>
              <th>Name</th>
              <th></ion-icon>Number ordered<a href="#"
              ></th>
              <th>Price</th>
              <th style="text-align: center">Remove</th>
            </tr>
          </thead>

          <tbody>

          <% @product_checkout_details.each do |product_checkout_detail| %>
              <tr>
                <th>
                  <%= image_tag Product.find_by(:name => product_checkout_detail.name).image, style: "width: 100px; height: 70px" %>

                </th>
                <th><%= product_checkout_detail.name %></th>
                <td ><div style="display: flex; align-items: center; gap: 10px">

                <%= button_to subtract_quantity_path(product_checkout_detail), method: :post, style: "background: none; border: none; padding: 0" do %>
                  <ion-icon
                name="remove-circle"
                style="color: #fd7e14; width: 28px; height: 28px"
              ></ion-icon>
                <% end %>
                <%= product_checkout_detail.quantity %>
                <%= button_to add_quantity_path(product_checkout_detail), method: :post, style: "background: none; border: none; padding: 0" do %>
                  <ion-icon
                name="add-circle"
                style="color: #fd7e14; width: 28px; height: 28px"
              ></ion-icon>
                <% end %>
                </div></td>
                <td><%= product_checkout_detail.price.to_i * product_checkout_detail.quantity.to_i %> VND</td>
                <td style="text-align: center">
                <%= button_to remove_product_in_cart_path(product_checkout_detail), method: :delete, style: "background: none; border: none; padding: 0" do %>
                    <ion-icon
                      name="trash-bin"
                      style="color: red; width: 30px; height: 30px"
                    ></ion-icon
                  ><% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="checkout--info--container">
      <p style="font-size: 2rem; margin-bottom: 1rem;">Total:</p>
      <p class="total--price--field">
        <% total = 0 %>
        <% @product_checkout_details.each do |product_checkout_detail| %>
        <% total += product_checkout_detail.price.to_i * product_checkout_detail.quantity.to_i %>
        <% end %>
        <%= total %>VND</p>
      <hr style="margin-top: 20px">

      <button class="orange-button show-modal">Buy now!</button>
      <%= button_to "Continue shopping", products_path, class: "green-button", method: :get  %>

    </div>
    <section class="section-cta modal hidden" style="background:none; padding: 0px; overflow: hidden">
    <div >
      <div class="cta">
        <button class="close-modal">&times;</button>
        <div class="cta-text-box">
          <h2 class="heading-secondary">Just one more step!</h2>
          <p class="cta-text">
            Your delicious meals are ready to be delivered to you. Just fill in your information
            so we can ship it to your house!
          </p>


          <%= form_with(url: checkout_path, local: true, method: :post, class: "cta-form") do |form| %>
            <div>
              <label for="full-name">Full Name</label>
              <%= form.text_field :name, size: "30", placeholder: "Nguyen Van Abc"%>
            </div>

            <div>
              <label for="phone">Your phone number</label>
              <%= form.text_field :phone, size: "30", placeholder: "092 1234 849"%>
            </div>


            <div>
              <label for="address">Your address</label>
              <%= form.text_field :address, size: "30", placeholder: "So 1 Dai Co Viet"%>
            </div>

            <%= button_to "Checkout", checkout_path, method: :post, class: "btn btn--form"%>
            <% end %>



        </div>
        <div
          class="cta-img-box"
          role="img"
          aria-label="Woman enjoying food"
          style="background-image: url(assets/meal-8.jpg)"
        ></div>
      </div>
    </div>
  </section>
  </main>

    <div class="overlay hidden"></div>
</body>

<script>

</script>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "products", "data-turbo-track": "reload" %>
<link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&display=swap"
      rel="stylesheet"/>

<p style="color: green"><%= notice %></p>

<body>
    <%= render 'header' %>
    <main>
      <%= render 'filter' %>
      <div
        class="container grid grid--4-cols margin-bottom-md"
        id="card-container">

        <% @products.each do |product| %>
          <%= render 'product', product: product %>
        <% end %>

      </div>

    </main>
    <div class="apple_pagination">
      <%= will_paginate @posts, :container => false %>
    </div>
  </body>
  <%= render 'manage-account'%>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>